### PR TITLE
Fixed Issue #25

### PR DESCRIPTION
**Pull request by SnowPowerCore**
## PR overview
This PR includes:
- Fix on NRE when applying this library on an invisible ShellContent instance.

## What's changed
- Android's shell item renderer.

## Actions required
- Nuget package needs to be updated;
- Sample project needs to be updated.

### CODE REVIEW

**Comment by galadril** [comment]
Thanks again, ill push a nuget and update the sample project

**Comment by galadril** [comment]
https://www.nuget.org/packages/Xam.Shell.Badge/1.0.14

**Comment by galadril** [comment]
Sample project is also updated

**Comment by SnowPowerCore** [comment]
Thank you, @galadril.

**Pull request merged**
