### PR TITLE
[Hotfix] Fix for tiny badge not displaying

### PR DESCRIPTION
**Pull request by SnowPowerCore**
## PR overview
This PR includes:
- Hotfix for visuals related to tiny badge display (both platforms) #11;

## Actions required
- Nuget package needs to be updated;
- Sample project needs to be updated;

### CODE REVIEW

**Comment by SnowPowerCore** [comment]
@galadril Hello, sorry, this took time, i was busy. If you have time, please, review it.

**Comment by SnowPowerCore** [comment]
@galadril, i know, you added me as a contributor (big thanks to that) and i got this green button "Merge PR"))) But i want you to approve this, at least by saying you're "ok" with only me reviewing/merging PRs if you are busy...

**Comment by galadril** [comment]
Cool thanks!

**Comment by galadril** [comment]
Updated the nuget package
image

**Comment by galadril** [comment]
I've also updated the sample project with a binding / viewmodel sample

**Pull request merged**
